  
import { ethers } from 'ethers'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Web3Modal from "web3modal"

import {
  nftaddress, nftmarketaddress
} from '../config'

/*This is importing autogenerated artifacts from the hardhat tests*/
import NFT from '../artifacts/contracts/NFT.sol/NFT.json'
import Market from '../artifacts/contracts/NFTMarket.sol/NFTMarket.json'

export default function Home() {
  // have an empty array of nfts and a way to set nfts
  const [nfts, setNfts] = useState([])
  // loading state is a var, and set can set it, helps us monitor when we are loading / loaded
  const [loadingState, setLoadingState] = useState('not-loaded')
  
  // this calls our loadNFT first thing when page loads
  useEffect(() => {
    loadNFTs()
  }, [])

  // call our smart contracts and load our NFT
  async function loadNFTs() {    
    const provider = new ethers.providers.JsonRpcProvider()
    // get the token info
    const tokenContract = new ethers.Contract(nftaddress, NFT.abi, provider)
    // get the market data
    const marketContract = new ethers.Contract(nftmarketaddress, Market.abi, provider)
    // our fetchMarketItems, unsold market items, from our .sol code
    const data = await marketContract.fetchMarketItems()
    
    //array called items and have some aysnc operations
    const items = await Promise.all(data.map(async i => {
      // URIs are intended to aid in identification of generated secrets
      const tokenUri = await tokenContract.tokenURI(i.tokenId)
      // this gets the metadata, name, image, etc. 
      const meta = await axios.get(tokenUri)
      // have to format to make price readable
      let price = ethers.utils.formatUnits(i.price.toString(), 'ether')
      let item = {
        price,
        tokenId: i.tokenId.toNumber(),
        seller: i.seller,
        owner: i.owner,
        image: meta.data.image,
        name: meta.data.name,
        description: meta.data.description,
      }
      return item
    }))
    //calls our set events up top 
    setNfts(items)
    setLoadingState('loaded') 
  }
  async function buyNft(nft) {
    // connect to the wallet 
    const web3Modal = new Web3Modal()
    const connection = await web3Modal.connect()
    // create a provider using the users connection
    const provider = new ethers.providers.Web3Provider(connection)
    // have provider be a signer
    const signer = provider.getSigner()
    const contract = new ethers.Contract(nftmarketaddress, Market.abi, signer)

    // get formatted price
    const price = ethers.utils.parseUnits(nft.price.toString(), 'ether')
    const transaction = await contract.createMarketSale(nftaddress, nft.tokenId, {
      value: price
    })
    await transaction.wait()
    // reload the page with loadNFT and newly bought NFT shouldn't appear
    loadNFTs()
  }

  if (loadingState === 'loaded' && !nfts.length) return (<h1 className="px-20 py-10 text-3xl">No items in marketplace</h1>)
  return (
    <div className="flex justify-center">
      <div className="px-4" style={{ maxWidth: '1600px' }}>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-4">
          {
            nfts.map((nft, i) => (
              <div key={i} className="border shadow rounded-xl overflow-hidden">
                <img src={nft.image} />
                <div className="p-4">
                  <p style={{ height: '64px' }} className="text-2xl font-semibold">{nft.name}</p>
                  <div style={{ height: '70px', overflow: 'hidden' }}>
                    <p className="text-gray-400">{nft.description}</p>
                  </div>
                </div>
                <div className="p-4 bg-black">
                  <p className="text-2xl mb-4 font-bold text-white">{nft.price} ETH</p>
                  <button className="w-full bg-pink-500 text-white font-bold py-2 px-12 rounded" onClick={() => buyNft(nft)}>Buy</button>
                </div>
              </div>
            ))
          }
        </div>
      </div>
    </div>
  )
}
